"""add cogs fields to retail sale item

Revision ID: 69db152a0dc6
Revises: c24bb3bfd61b
Create Date: 2025-08-15 13:33:38.162101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69db152a0dc6'
down_revision = 'c24bb3bfd61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price_carton', sa.Float(), nullable=True))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_expense_date'), ['date'], unique=False)

    with op.batch_alter_table('retail_sale', schema=None) as batch_op:
        batch_op.create_index('ix_retail_sale_date', ['date'], unique=False)

    with op.batch_alter_table('retail_sale_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cogs_unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cogs_total', sa.Float(), nullable=True))
        batch_op.create_index('ix_rsi_bottle_size_id', ['bottle_size_id'], unique=False)
        batch_op.create_index('ix_rsi_sale_id', ['sale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retail_sale_item', schema=None) as batch_op:
        batch_op.drop_index('ix_rsi_sale_id')
        batch_op.drop_index('ix_rsi_bottle_size_id')
        batch_op.drop_column('cogs_total')
        batch_op.drop_column('cogs_unit_price')

    with op.batch_alter_table('retail_sale', schema=None) as batch_op:
        batch_op.drop_index('ix_retail_sale_date')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_date'))
        batch_op.drop_column('payment_method')
        batch_op.drop_column('category')

    with op.batch_alter_table('bottle_size', schema=None) as batch_op:
        batch_op.drop_column('cost_price_carton')

    # ### end Alembic commands ###
